set(EMC_USB_VENDOR_CELENO_CLI_TARGET_MEM "MMAP" CACHE STRING "")
set_property(CACHE EMC_USB_VENDOR_CELENO_CLI_TARGET_MEM PROPERTY STRINGS "DIRECT" "VIRTUAL" "MMAP")

set(EMC_USB_VENDOR_CELENO_CLI_LOG_LEVEL ${EMC_LOG_LEVEL} CACHE STRING "")
set_property(CACHE EMC_USB_VENDOR_CELENO_CLI_LOG_LEVEL PROPERTY STRINGS "TRACE" "DEBUG" "INFO" "WARN" "ERROR" "FATAL" "OFF")

