/* Copyright (C) 2011-2013 emsys Embedded Systems GmbH */
#include "emc/usb/Error.h"

const char* EMC_USB_Error_name(EMC_USB_Error error)
{
#if EMC_PRINT
  if (error == EMC_USB_NO_ERROR) {
    return "USB NO ERROR";
  } else if ((error >= EMC_USB_ERROR_MIN) && (error <= EMC_USB_ERROR_MAX)) {
    static const char* const names[] = {
      "EMC_USB_ERR_DRIVER_NOT_INITIALIZED",
      "EMC_USB_ERR_DRIVER_NOT_OPENED",
      "EMC_USB_ERR_UNKNOWN_PARAMETER",
      "EMC_USB_ERR_NON_VALID_ENDPOINT",

      "EMC_USB_ERR_BUFFER_SIZE_ERROR",
      "EMC_USB_ERR_BUFFER_DIR_MISMATCH",
      "EMC_USB_ERR_NO_REQUEST_PENDING",
      "EMC_USB_ERR_NO_DATA_STAGE_PENDING",

      "EMC_USB_ERR_NO_STATUS_STAGE_PENDING",
      "EMC_USB_ERR_NO_REMOTE_WAKEUP_ALLOWED",
      "EMC_USB_ERR_DEVICE_NOT_SUSPENDED",
      "EMC_USB_ERR_DEVICE_NOT_ACTIVE",

      "EMC_USB_ERR_BUFFER_OVERLAPPING",
      "EMC_USB_ERR_EP_STALLED",
      "EMC_USB_ERR_EP0_STALLED",
      "EMC_USB_ERR_INTERNAL_ERROR",

      "EMC_USB_ERR_NO_FREE_EP_INFO",
      "EMC_USB_ERR_REINITIALIZE_EP_INFO",
      "EMC_USB_ERR_UNSPECIFIED_BEHAVIOR",
      "EMC_USB_ERR_UNSUPPORTED_REQUEST",
      "EMC_USB_ERR_UNSUPPORTED_DEVICE_FEATURE",
      "EMC_USB_ERR_UNSUPPORTED_INTERFACE_FEATURE",
      "EMC_USB_ERR_UNSUPPORTED_ENDPOINT_FEATURE",
      "EMC_USB_ERR_REQUEST_INVALID_VALUE",
      "EMC_USB_ERR_REQUEST_INVALID_LENGTH",
      "EMC_USB_ERR_REQUEST_INVALID_INDEX",
      "EMC_USB_ERR_UNKNOWN_INTERFACE",
      "EMC_USB_ERR_UNKNOWN_ENDPOINT",
      "EMC_USB_ERR_UNKNOWN_RECIPIENT",
      "EMC_USB_ERR_INVALID_DESCRIPTOR",
      "EMC_USB_ERR_INVALID_ADDRESS",
      "EMC_USB_ERR_APPLICATION_ERROR",
      "EMC_USB_ERR_NO_STALL_ON_EP0"
    };
    return names[error - EMC_USB_ERROR_MIN];
  } else {
    return "USB unspecified error!";
  }
#else
  UNUSED_PARAM(error);
  return "unknown";
#endif
}
