PROJECT.ROOT.PATHNAME ?= ../..

include $(PROJECT.ROOT.PATHNAME)/../eme/makefiles/makefile_setup.mk

SUBDIRS :=
SUBDIRS += Framework
SUBDIRS += Console
SUBDIRS += Automated
#SUBDIRS += Curses

include $(MAKE.DIR)/makefile_emsys.mk
