#ifndef _CL_FEM_REGS_H_
#define _CL_FEM_REGS_H_

#include "reg_riu_rc.h"
#include "reg_io_ctrl.h"

//#define uint16_t uint16_t

/*********************************/
/*      List of FEM types:       */
/*                               */
/* FEM_ID_0 - SKY85746_11_5G     */
/* FEM_ID_1 - SKY85330_21_24G    */
/* FEM_ID_2 - SKY85818_11_MIX    */
/*                               */
/*********************************/

// SKY85746_11_5G
#define FEM_ID_0_RX_LNA_BYPASS (uint16_t)0b100
#define FEM_ID_0_TX            (uint16_t)0b001
#define FEM_ID_0_RX            (uint16_t)0b110
#define FEM_ID_0_OFF           (uint16_t)0b000

// FEM_ID_0_LUT = 0x0614
#define FEM_ID_0_LUT (uint16_t)(((FEM_ID_0_RX_LNA_BYPASS << RIU_RC_RF_LNA_LUT_RFLNALUT_0_LSB) & RIU_RC_RF_LNA_LUT_RFLNALUT_0_MASK) |\
			   ((FEM_ID_0_TX            << RIU_RC_RF_LNA_LUT_RFLNALUT_1_LSB) & RIU_RC_RF_LNA_LUT_RFLNALUT_1_MASK) |\
			   ((FEM_ID_0_RX            << RIU_RC_RF_LNA_LUT_RFLNALUT_2_LSB) & RIU_RC_RF_LNA_LUT_RFLNALUT_2_MASK))

// FEM_ID_0_LUT_OFF = 0x0000
#define FEM_ID_0_LUT_OFF (uint16_t)(((FEM_ID_0_OFF << RIU_RC_RF_LNA_LUT_RFLNALUT_0_LSB) & RIU_RC_RF_LNA_LUT_RFLNALUT_0_MASK) |\
			       ((FEM_ID_0_OFF << RIU_RC_RF_LNA_LUT_RFLNALUT_1_LSB) & RIU_RC_RF_LNA_LUT_RFLNALUT_1_MASK) |\
			       ((FEM_ID_0_OFF << RIU_RC_RF_LNA_LUT_RFLNALUT_2_LSB) & RIU_RC_RF_LNA_LUT_RFLNALUT_2_MASK))

/*******************************************************************************************************/

// SKY85330_21_24G
#define FEM_ID_1_RX_LNA_BYPASS (uint16_t)0b00
#define FEM_ID_1_TX            (uint16_t)0b01
#define FEM_ID_1_RX            (uint16_t)0b10
#define FEM_ID_1_OFF           (uint16_t)FEM_ID_1_RX_LNA_BYPASS

// FEM_ID_1_LUT = 0x0210
#define FEM_ID_1_LUT (uint16_t)(((FEM_ID_1_RX_LNA_BYPASS << RIU_RC_RF_LNA_LUT_RFLNALUT_0_LSB) & RIU_RC_RF_LNA_LUT_RFLNALUT_0_MASK) |\
			   ((FEM_ID_1_TX            << RIU_RC_RF_LNA_LUT_RFLNALUT_1_LSB) & RIU_RC_RF_LNA_LUT_RFLNALUT_1_MASK) |\
			   ((FEM_ID_1_RX            << RIU_RC_RF_LNA_LUT_RFLNALUT_2_LSB) & RIU_RC_RF_LNA_LUT_RFLNALUT_2_MASK))

// FEM_ID_1_LUT_OFF = 0x0000
#define FEM_ID_1_LUT_OFF (uint16_t)(((FEM_ID_1_OFF << RIU_RC_RF_LNA_LUT_RFLNALUT_0_LSB) & RIU_RC_RF_LNA_LUT_RFLNALUT_0_MASK) |\
			       ((FEM_ID_1_OFF << RIU_RC_RF_LNA_LUT_RFLNALUT_1_LSB) & RIU_RC_RF_LNA_LUT_RFLNALUT_1_MASK) |\
			       ((FEM_ID_1_OFF << RIU_RC_RF_LNA_LUT_RFLNALUT_2_LSB) & RIU_RC_RF_LNA_LUT_RFLNALUT_2_MASK))

#define FEM_LUT_EMPTY (uint16_t)0x0000

/*******************************************************************************************************/

// SKY85818_11_MIX
#define FEM_ID_2_RX_LNA_BYPASS (uint16_t)0b001
#define FEM_ID_2_TX            (uint16_t)0b011
#define FEM_ID_2_RX            (uint16_t)0b000
#define FEM_ID_2_OFF           (uint16_t)FEM_ID_2_RX_LNA_BYPASS
// FEM_ID_2_LUT = 0x0031
#define FEM_ID_2_LUT (uint16_t)(((FEM_ID_2_RX_LNA_BYPASS << RIU_RC_RF_LNA_LUT_RFLNALUT_0_LSB) & RIU_RC_RF_LNA_LUT_RFLNALUT_0_MASK) |\
			   ((FEM_ID_2_TX            << RIU_RC_RF_LNA_LUT_RFLNALUT_1_LSB) & RIU_RC_RF_LNA_LUT_RFLNALUT_1_MASK) |\
			   ((FEM_ID_2_RX            << RIU_RC_RF_LNA_LUT_RFLNALUT_2_LSB) & RIU_RC_RF_LNA_LUT_RFLNALUT_2_MASK))

// FEM_ID_2_LUT_OFF = 0x0111
#define FEM_ID_2_LUT_OFF (uint16_t)(((FEM_ID_2_OFF << RIU_RC_RF_LNA_LUT_RFLNALUT_0_LSB) & RIU_RC_RF_LNA_LUT_RFLNALUT_0_MASK) |\
			       ((FEM_ID_2_OFF << RIU_RC_RF_LNA_LUT_RFLNALUT_1_LSB) & RIU_RC_RF_LNA_LUT_RFLNALUT_1_MASK) |\
			       ((FEM_ID_2_OFF << RIU_RC_RF_LNA_LUT_RFLNALUT_2_LSB) & RIU_RC_RF_LNA_LUT_RFLNALUT_2_MASK))


// FEM_CON_0
#define RICU_FEM_CONF_0_PLATFORM_0_AP231_AP232 (u32)0x00AB3021
#define RICU_FEM_CONF_0_PLATFORM_1_AP235       (u32)0x00000001
#define RICU_FEM_CONF_0_PLATFORM_2_AP236       (u32)0x00003021

// FEM_CON_1
#define RICU_FEM_CONF_1_PLATFORM_0_AP231_AP232 (u32)0x0054CD89
#define RICU_FEM_CONF_1_PLATFORM_1_AP235       (u32)0x0032AB89
#define RICU_FEM_CONF_1_PLATFORM_2_AP236       (u32)0x00AB0089

// Platform ID 0 - AP231, AP232
#define LNA_ENABLE_0_PLAT_0_GPIO_ENABLE  ((0 << IO_CTRL_LNA_ENABLE_0_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_0_GPIO_ENABLE_BIT)
#define LNA_ENABLE_1_PLAT_0_GPIO_ENABLE  ((0 << IO_CTRL_LNA_ENABLE_1_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_1_GPIO_ENABLE_BIT)
#define LNA_ENABLE_2_PLAT_0_GPIO_ENABLE  ((0 << IO_CTRL_LNA_ENABLE_2_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_2_GPIO_ENABLE_BIT)
#define LNA_ENABLE_3_PLAT_0_GPIO_ENABLE  ((0 << IO_CTRL_LNA_ENABLE_3_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_3_GPIO_ENABLE_BIT)
#define LNA_ENABLE_4_PLAT_0_GPIO_ENABLE  ((0 << IO_CTRL_LNA_ENABLE_4_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_4_GPIO_ENABLE_BIT)
#define LNA_ENABLE_5_PLAT_0_GPIO_ENABLE  ((0 << IO_CTRL_LNA_ENABLE_5_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_5_GPIO_ENABLE_BIT)
#define LNA_ENABLE_6_PLAT_0_GPIO_ENABLE  ((0 << IO_CTRL_LNA_ENABLE_6_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_6_GPIO_ENABLE_BIT)
#define LNA_ENABLE_7_PLAT_0_GPIO_ENABLE  ((0 << IO_CTRL_LNA_ENABLE_7_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_7_GPIO_ENABLE_BIT)
#define LNA_ENABLE_8_PLAT_0_GPIO_ENABLE  ((0 << IO_CTRL_LNA_ENABLE_8_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_8_GPIO_ENABLE_BIT)
#define LNA_ENABLE_9_PLAT_0_GPIO_ENABLE  ((0 << IO_CTRL_LNA_ENABLE_9_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_9_GPIO_ENABLE_BIT)
#define LNA_ENABLE_10_PLAT_0_GPIO_ENABLE ((0 << IO_CTRL_LNA_ENABLE_10_GPIO_ENABLE_POS) & IO_CTRL_LNA_ENABLE_10_GPIO_ENABLE_BIT)
#define LNA_ENABLE_11_PLAT_0_GPIO_ENABLE ((0 << IO_CTRL_LNA_ENABLE_11_GPIO_ENABLE_POS) & IO_CTRL_LNA_ENABLE_11_GPIO_ENABLE_BIT)

#define PA_ENABLE_0_PLAT_0_GPIO_ENABLE  ((0 << IO_CTRL_PA_ENABLE_0_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_0_GPIO_ENABLE_BIT)
#define PA_ENABLE_1_PLAT_0_GPIO_ENABLE  ((0 << IO_CTRL_PA_ENABLE_1_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_1_GPIO_ENABLE_BIT)
#define PA_ENABLE_2_PLAT_0_GPIO_ENABLE  ((0 << IO_CTRL_PA_ENABLE_2_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_2_GPIO_ENABLE_BIT)
#define PA_ENABLE_3_PLAT_0_GPIO_ENABLE  ((0 << IO_CTRL_PA_ENABLE_3_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_3_GPIO_ENABLE_BIT)
#define PA_ENABLE_4_PLAT_0_GPIO_ENABLE  ((0 << IO_CTRL_PA_ENABLE_4_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_4_GPIO_ENABLE_BIT)
#define PA_ENABLE_5_PLAT_0_GPIO_ENABLE  ((0 << IO_CTRL_PA_ENABLE_5_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_5_GPIO_ENABLE_BIT)
#define PA_ENABLE_6_PLAT_0_GPIO_ENABLE  ((0 << IO_CTRL_PA_ENABLE_6_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_6_GPIO_ENABLE_BIT) //Set to 1 when in imaging mode (PA is not connected)
#define PA_ENABLE_7_PLAT_0_GPIO_ENABLE  ((0 << IO_CTRL_PA_ENABLE_7_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_7_GPIO_ENABLE_BIT) //Set to 1 when in imaging mode (PA is not connected)
#define PA_ENABLE_8_PLAT_0_GPIO_ENABLE  ((0 << IO_CTRL_PA_ENABLE_8_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_8_GPIO_ENABLE_BIT)
#define PA_ENABLE_9_PLAT_0_GPIO_ENABLE  ((0 << IO_CTRL_PA_ENABLE_9_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_9_GPIO_ENABLE_BIT)
#define PA_ENABLE_10_PLAT_0_GPIO_ENABLE ((0 << IO_CTRL_PA_ENABLE_10_GPIO_ENABLE_POS) & IO_CTRL_PA_ENABLE_10_GPIO_ENABLE_BIT)
#define PA_ENABLE_11_PLAT_0_GPIO_ENABLE ((0 << IO_CTRL_PA_ENABLE_11_GPIO_ENABLE_POS) & IO_CTRL_PA_ENABLE_11_GPIO_ENABLE_BIT)

#define RX_ACTIVE0_PLAT_0_GPIO_ENABLE ((0 << IO_CTRL_RX_ACTIVE_0_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_0_GPIO_ENABLE_BIT)
#define RX_ACTIVE1_PLAT_0_GPIO_ENABLE ((0 << IO_CTRL_RX_ACTIVE_1_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_1_GPIO_ENABLE_BIT)
#define RX_ACTIVE2_PLAT_0_GPIO_ENABLE ((0 << IO_CTRL_RX_ACTIVE_2_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_2_GPIO_ENABLE_BIT)
#define RX_ACTIVE3_PLAT_0_GPIO_ENABLE ((0 << IO_CTRL_RX_ACTIVE_3_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_3_GPIO_ENABLE_BIT)
#define RX_ACTIVE4_PLAT_0_GPIO_ENABLE ((0 << IO_CTRL_RX_ACTIVE_4_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_4_GPIO_ENABLE_BIT)
#define RX_ACTIVE5_PLAT_0_GPIO_ENABLE ((0 << IO_CTRL_RX_ACTIVE_5_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_5_GPIO_ENABLE_BIT)
#define RX_ACTIVE6_PLAT_0_GPIO_ENABLE ((1 << IO_CTRL_RX_ACTIVE_6_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_6_GPIO_ENABLE_BIT) //because line is not used by 2.4G FEM
#define RX_ACTIVE7_PLAT_0_GPIO_ENABLE ((1 << IO_CTRL_RX_ACTIVE_7_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_7_GPIO_ENABLE_BIT) //Test Point, line is not used by 2.4G FEM

// Platform ID 1 - AP235
#define LNA_ENABLE_0_PLAT_1_GPIO_ENABLE  ((0 << IO_CTRL_LNA_ENABLE_0_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_0_GPIO_ENABLE_BIT)
#define LNA_ENABLE_1_PLAT_1_GPIO_ENABLE  ((1 << IO_CTRL_LNA_ENABLE_1_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_1_GPIO_ENABLE_BIT) //FEM not connected, therefore GPIO is enabled
#define LNA_ENABLE_2_PLAT_1_GPIO_ENABLE  ((0 << IO_CTRL_LNA_ENABLE_2_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_2_GPIO_ENABLE_BIT)
#define LNA_ENABLE_3_PLAT_1_GPIO_ENABLE  ((1 << IO_CTRL_LNA_ENABLE_3_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_3_GPIO_ENABLE_BIT) //FEM not connected, therefore GPIO is enabled
#define LNA_ENABLE_4_PLAT_1_GPIO_ENABLE  ((1 << IO_CTRL_LNA_ENABLE_4_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_4_GPIO_ENABLE_BIT) //FEM not connected, therefore GPIO is enabled
#define LNA_ENABLE_5_PLAT_1_GPIO_ENABLE  ((1 << IO_CTRL_LNA_ENABLE_5_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_5_GPIO_ENABLE_BIT) //FEM not connected, therefore GPIO is enabled
#define LNA_ENABLE_6_PLAT_1_GPIO_ENABLE  ((0 << IO_CTRL_LNA_ENABLE_6_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_6_GPIO_ENABLE_BIT)
#define LNA_ENABLE_7_PLAT_1_GPIO_ENABLE  ((0 << IO_CTRL_LNA_ENABLE_7_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_7_GPIO_ENABLE_BIT)
#define LNA_ENABLE_8_PLAT_1_GPIO_ENABLE  ((0 << IO_CTRL_LNA_ENABLE_8_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_8_GPIO_ENABLE_BIT)
#define LNA_ENABLE_9_PLAT_1_GPIO_ENABLE  ((0 << IO_CTRL_LNA_ENABLE_9_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_9_GPIO_ENABLE_BIT)
#define LNA_ENABLE_10_PLAT_1_GPIO_ENABLE ((0 << IO_CTRL_LNA_ENABLE_10_GPIO_ENABLE_POS) & IO_CTRL_LNA_ENABLE_10_GPIO_ENABLE_BIT)
#define LNA_ENABLE_11_PLAT_1_GPIO_ENABLE ((0 << IO_CTRL_LNA_ENABLE_11_GPIO_ENABLE_POS) & IO_CTRL_LNA_ENABLE_11_GPIO_ENABLE_BIT)

#define PA_ENABLE_0_PLAT_1_GPIO_ENABLE  ((0 << IO_CTRL_PA_ENABLE_0_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_0_GPIO_ENABLE_BIT)
#define PA_ENABLE_1_PLAT_1_GPIO_ENABLE  ((1 << IO_CTRL_PA_ENABLE_1_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_1_GPIO_ENABLE_BIT) //FEM not connected, therefore GPIO is enabled
#define PA_ENABLE_2_PLAT_1_GPIO_ENABLE  ((0 << IO_CTRL_PA_ENABLE_2_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_2_GPIO_ENABLE_BIT)
#define PA_ENABLE_3_PLAT_1_GPIO_ENABLE  ((1 << IO_CTRL_PA_ENABLE_3_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_3_GPIO_ENABLE_BIT) //FEM not connected, therefore GPIO is enabled
#define PA_ENABLE_4_PLAT_1_GPIO_ENABLE  ((1 << IO_CTRL_PA_ENABLE_4_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_4_GPIO_ENABLE_BIT) //FEM not connected, therefore GPIO is enabled
#define PA_ENABLE_5_PLAT_1_GPIO_ENABLE  ((1 << IO_CTRL_PA_ENABLE_5_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_5_GPIO_ENABLE_BIT) //FEM not connected, therefore GPIO is enabled
#define PA_ENABLE_6_PLAT_1_GPIO_ENABLE  ((0 << IO_CTRL_PA_ENABLE_6_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_6_GPIO_ENABLE_BIT)
#define PA_ENABLE_7_PLAT_1_GPIO_ENABLE  ((0 << IO_CTRL_PA_ENABLE_7_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_7_GPIO_ENABLE_BIT)
#define PA_ENABLE_8_PLAT_1_GPIO_ENABLE  ((0 << IO_CTRL_PA_ENABLE_8_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_8_GPIO_ENABLE_BIT)
#define PA_ENABLE_9_PLAT_1_GPIO_ENABLE  ((0 << IO_CTRL_PA_ENABLE_9_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_9_GPIO_ENABLE_BIT)
#define PA_ENABLE_10_PLAT_1_GPIO_ENABLE ((0 << IO_CTRL_PA_ENABLE_10_GPIO_ENABLE_POS) & IO_CTRL_PA_ENABLE_10_GPIO_ENABLE_BIT)
#define PA_ENABLE_11_PLAT_1_GPIO_ENABLE ((0 << IO_CTRL_PA_ENABLE_11_GPIO_ENABLE_POS) & IO_CTRL_PA_ENABLE_11_GPIO_ENABLE_BIT)

#define RX_ACTIVE0_PLAT_1_GPIO_ENABLE ((0 << IO_CTRL_RX_ACTIVE_0_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_0_GPIO_ENABLE_BIT) //used for 5G FEM
#define RX_ACTIVE1_PLAT_1_GPIO_ENABLE ((0 << IO_CTRL_RX_ACTIVE_1_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_1_GPIO_ENABLE_BIT) //used for 5G FEM
#define RX_ACTIVE2_PLAT_1_GPIO_ENABLE ((0 << IO_CTRL_RX_ACTIVE_2_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_2_GPIO_ENABLE_BIT) //used for 5G FEM
#define RX_ACTIVE3_PLAT_1_GPIO_ENABLE ((0 << IO_CTRL_RX_ACTIVE_3_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_3_GPIO_ENABLE_BIT) //used for 5G FEM
#define RX_ACTIVE4_PLAT_1_GPIO_ENABLE ((1 << IO_CTRL_RX_ACTIVE_4_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_4_GPIO_ENABLE_BIT)
#define RX_ACTIVE5_PLAT_1_GPIO_ENABLE ((1 << IO_CTRL_RX_ACTIVE_5_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_5_GPIO_ENABLE_BIT)
#define RX_ACTIVE6_PLAT_1_GPIO_ENABLE ((1 << IO_CTRL_RX_ACTIVE_6_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_6_GPIO_ENABLE_BIT)
#define RX_ACTIVE7_PLAT_1_GPIO_ENABLE ((1 << IO_CTRL_RX_ACTIVE_7_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_7_GPIO_ENABLE_BIT)

// Platform ID 2 - AP236
#define LNA_ENABLE_0_PLAT_2_GPIO_ENABLE  ((0 << IO_CTRL_LNA_ENABLE_0_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_0_GPIO_ENABLE_BIT)
#define LNA_ENABLE_1_PLAT_2_GPIO_ENABLE  ((0 << IO_CTRL_LNA_ENABLE_1_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_1_GPIO_ENABLE_BIT)
#define LNA_ENABLE_2_PLAT_2_GPIO_ENABLE  ((0 << IO_CTRL_LNA_ENABLE_2_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_2_GPIO_ENABLE_BIT)
#define LNA_ENABLE_3_PLAT_2_GPIO_ENABLE  ((0 << IO_CTRL_LNA_ENABLE_3_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_3_GPIO_ENABLE_BIT)
#define LNA_ENABLE_4_PLAT_2_GPIO_ENABLE  ((1 << IO_CTRL_LNA_ENABLE_4_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_4_GPIO_ENABLE_BIT) //FEM not connected, therefore GPIO is enabled
#define LNA_ENABLE_5_PLAT_2_GPIO_ENABLE  ((1 << IO_CTRL_LNA_ENABLE_5_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_5_GPIO_ENABLE_BIT) //FEM not connected, therefore GPIO is enabled
#define LNA_ENABLE_6_PLAT_2_GPIO_ENABLE  ((0 << IO_CTRL_LNA_ENABLE_6_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_6_GPIO_ENABLE_BIT)
#define LNA_ENABLE_7_PLAT_2_GPIO_ENABLE  ((0 << IO_CTRL_LNA_ENABLE_7_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_7_GPIO_ENABLE_BIT)
#define LNA_ENABLE_8_PLAT_2_GPIO_ENABLE  ((1 << IO_CTRL_LNA_ENABLE_8_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_8_GPIO_ENABLE_BIT) //FEM not connected, therefore GPIO is enabled
#define LNA_ENABLE_9_PLAT_2_GPIO_ENABLE  ((1 << IO_CTRL_LNA_ENABLE_9_GPIO_ENABLE_POS)  & IO_CTRL_LNA_ENABLE_9_GPIO_ENABLE_BIT) //FEM not connected, therefore GPIO is enabled
#define LNA_ENABLE_10_PLAT_2_GPIO_ENABLE ((0 << IO_CTRL_LNA_ENABLE_10_GPIO_ENABLE_POS) & IO_CTRL_LNA_ENABLE_10_GPIO_ENABLE_BIT)
#define LNA_ENABLE_11_PLAT_2_GPIO_ENABLE ((0 << IO_CTRL_LNA_ENABLE_11_GPIO_ENABLE_POS) & IO_CTRL_LNA_ENABLE_11_GPIO_ENABLE_BIT)

#define PA_ENABLE_0_PLAT_2_GPIO_ENABLE  ((0 << IO_CTRL_PA_ENABLE_0_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_0_GPIO_ENABLE_BIT)
#define PA_ENABLE_1_PLAT_2_GPIO_ENABLE  ((1 << IO_CTRL_PA_ENABLE_1_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_1_GPIO_ENABLE_BIT)
#define PA_ENABLE_2_PLAT_2_GPIO_ENABLE  ((0 << IO_CTRL_PA_ENABLE_2_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_2_GPIO_ENABLE_BIT)
#define PA_ENABLE_3_PLAT_2_GPIO_ENABLE  ((0 << IO_CTRL_PA_ENABLE_3_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_3_GPIO_ENABLE_BIT)
#define PA_ENABLE_4_PLAT_2_GPIO_ENABLE  ((1 << IO_CTRL_PA_ENABLE_4_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_4_GPIO_ENABLE_BIT) //Band Select FEM4
#define PA_ENABLE_5_PLAT_2_GPIO_ENABLE  ((1 << IO_CTRL_PA_ENABLE_5_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_5_GPIO_ENABLE_BIT) //Band Select FEM5
#define PA_ENABLE_6_PLAT_2_GPIO_ENABLE  ((0 << IO_CTRL_PA_ENABLE_6_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_6_GPIO_ENABLE_BIT)
#define PA_ENABLE_7_PLAT_2_GPIO_ENABLE  ((0 << IO_CTRL_PA_ENABLE_7_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_7_GPIO_ENABLE_BIT)
#define PA_ENABLE_8_PLAT_2_GPIO_ENABLE  ((1 << IO_CTRL_PA_ENABLE_8_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_8_GPIO_ENABLE_BIT) //Band Select FEM2
#define PA_ENABLE_9_PLAT_2_GPIO_ENABLE  ((1 << IO_CTRL_PA_ENABLE_9_GPIO_ENABLE_POS)  & IO_CTRL_PA_ENABLE_9_GPIO_ENABLE_BIT) //Band Select FEM3
#define PA_ENABLE_10_PLAT_2_GPIO_ENABLE ((0 << IO_CTRL_PA_ENABLE_10_GPIO_ENABLE_POS) & IO_CTRL_PA_ENABLE_10_GPIO_ENABLE_BIT)
#define PA_ENABLE_11_PLAT_2_GPIO_ENABLE ((0 << IO_CTRL_PA_ENABLE_11_GPIO_ENABLE_POS) & IO_CTRL_PA_ENABLE_11_GPIO_ENABLE_BIT)

#define RX_ACTIVE0_PLAT_2_GPIO_ENABLE ((0 << IO_CTRL_RX_ACTIVE_0_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_0_GPIO_ENABLE_BIT) //used for 5G FEM
#define RX_ACTIVE1_PLAT_2_GPIO_ENABLE ((0 << IO_CTRL_RX_ACTIVE_1_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_1_GPIO_ENABLE_BIT) //used for 5G FEM
#define RX_ACTIVE2_PLAT_2_GPIO_ENABLE ((1 << IO_CTRL_RX_ACTIVE_2_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_2_GPIO_ENABLE_BIT)
#define RX_ACTIVE3_PLAT_2_GPIO_ENABLE ((1 << IO_CTRL_RX_ACTIVE_3_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_3_GPIO_ENABLE_BIT)
#define RX_ACTIVE4_PLAT_2_GPIO_ENABLE ((1 << IO_CTRL_RX_ACTIVE_4_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_4_GPIO_ENABLE_BIT)
#define RX_ACTIVE5_PLAT_2_GPIO_ENABLE ((1 << IO_CTRL_RX_ACTIVE_5_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_5_GPIO_ENABLE_BIT)
#define RX_ACTIVE6_PLAT_2_GPIO_ENABLE ((1 << IO_CTRL_RX_ACTIVE_6_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_6_GPIO_ENABLE_BIT)
#define RX_ACTIVE7_PLAT_2_GPIO_ENABLE ((1 << IO_CTRL_RX_ACTIVE_7_GPIO_ENABLE_POS)  & IO_CTRL_RX_ACTIVE_7_GPIO_ENABLE_BIT)

#define PA_ENABLE_4_PLAT_2_GPIO_OE ((1 << IO_CTRL_PA_ENABLE_4_GPIO_OE_POS)  & IO_CTRL_PA_ENABLE_4_GPIO_OE_BIT)
#define PA_ENABLE_5_PLAT_2_GPIO_OE ((1 << IO_CTRL_PA_ENABLE_5_GPIO_OE_POS)  & IO_CTRL_PA_ENABLE_5_GPIO_OE_BIT)
#define PA_ENABLE_8_PLAT_2_GPIO_OE ((1 << IO_CTRL_PA_ENABLE_8_GPIO_OE_POS)  & IO_CTRL_PA_ENABLE_8_GPIO_OE_BIT)
#define PA_ENABLE_9_PLAT_2_GPIO_OE ((1 << IO_CTRL_PA_ENABLE_9_GPIO_OE_POS)  & IO_CTRL_PA_ENABLE_9_GPIO_OE_BIT)

#define PA_ENABLE_4_PLAT_2_INPUT_ENABLE ((0 << IO_CTRL_PA_ENABLE_4_INPUT_ENABLE_POS)  & IO_CTRL_PA_ENABLE_4_INPUT_ENABLE_BIT)
#define PA_ENABLE_5_PLAT_2_INPUT_ENABLE ((0 << IO_CTRL_PA_ENABLE_5_INPUT_ENABLE_POS)  & IO_CTRL_PA_ENABLE_5_INPUT_ENABLE_BIT)
#define PA_ENABLE_8_PLAT_2_INPUT_ENABLE ((0 << IO_CTRL_PA_ENABLE_8_INPUT_ENABLE_POS)  & IO_CTRL_PA_ENABLE_8_INPUT_ENABLE_BIT)
#define PA_ENABLE_9_PLAT_2_INPUT_ENABLE ((0 << IO_CTRL_PA_ENABLE_9_INPUT_ENABLE_POS)  & IO_CTRL_PA_ENABLE_9_INPUT_ENABLE_BIT)

#define PA_ENABLE_4_PLAT_2_GPIO_OUT_5G ((1 << IO_CTRL_PA_ENABLE_4_GPIO_OUT_POS)  & IO_CTRL_PA_ENABLE_4_GPIO_OUT_BIT)
#define PA_ENABLE_5_PLAT_2_GPIO_OUT_5G ((1 << IO_CTRL_PA_ENABLE_5_GPIO_OUT_POS)  & IO_CTRL_PA_ENABLE_5_GPIO_OUT_BIT)
#define PA_ENABLE_8_PLAT_2_GPIO_OUT_5G ((1 << IO_CTRL_PA_ENABLE_8_GPIO_OUT_POS)  & IO_CTRL_PA_ENABLE_8_GPIO_OUT_BIT)
#define PA_ENABLE_9_PLAT_2_GPIO_OUT_5G ((1 << IO_CTRL_PA_ENABLE_9_GPIO_OUT_POS)  & IO_CTRL_PA_ENABLE_9_GPIO_OUT_BIT)

#define PA_ENABLE_4_PLAT_2_GPIO_OUT_24G ((0 << IO_CTRL_PA_ENABLE_4_GPIO_OUT_POS)  & IO_CTRL_PA_ENABLE_4_GPIO_OUT_BIT)
#define PA_ENABLE_5_PLAT_2_GPIO_OUT_24G ((0 << IO_CTRL_PA_ENABLE_5_GPIO_OUT_POS)  & IO_CTRL_PA_ENABLE_5_GPIO_OUT_BIT)
#define PA_ENABLE_8_PLAT_2_GPIO_OUT_24G ((0 << IO_CTRL_PA_ENABLE_8_GPIO_OUT_POS)  & IO_CTRL_PA_ENABLE_8_GPIO_OUT_BIT)
#define PA_ENABLE_9_PLAT_2_GPIO_OUT_24G ((0 << IO_CTRL_PA_ENABLE_9_GPIO_OUT_POS)  & IO_CTRL_PA_ENABLE_9_GPIO_OUT_BIT)



#define PA_ENABLE_4_PLAT_2_VALUE (PA_ENABLE_4_PLAT_2_GPIO_ENABLE | PA_ENABLE_4_PLAT_2_GPIO_OE | PA_ENABLE_4_PLAT_2_INPUT_ENABLE)
#define PA_ENABLE_5_PLAT_2_VALUE (PA_ENABLE_5_PLAT_2_GPIO_ENABLE | PA_ENABLE_5_PLAT_2_GPIO_OE | PA_ENABLE_5_PLAT_2_INPUT_ENABLE)
#define PA_ENABLE_8_PLAT_2_VALUE (PA_ENABLE_8_PLAT_2_GPIO_ENABLE | PA_ENABLE_8_PLAT_2_GPIO_OE | PA_ENABLE_8_PLAT_2_INPUT_ENABLE)
#define PA_ENABLE_9_PLAT_2_VALUE (PA_ENABLE_9_PLAT_2_GPIO_ENABLE | PA_ENABLE_9_PLAT_2_GPIO_OE | PA_ENABLE_9_PLAT_2_INPUT_ENABLE)


#endif //_CL_FEM_H_