#ifndef _PLATFORM_H_
#define _PLATFORM_H_

typedef enum
{
    CL_PLATFORM_ASIC_IDX,
    CL_PLATFORM_PALLADIUM_IDX,
    CL_PLATFORM_PROTIUM_IDX,
    CL_PLATFORM_B2B_IDX,
    CL_PLATFORM_B2B_LB_IDX,
    CL_PLATFORM_MAX_IDX
} CL_PLATFORM_IDX;

#endif