/*************************************************************************/
/*                                                                       */
/*                          Copyright INOMIZE                            */
/*                         All Rights Reserved.                          */
/*                                                                       */
/*            This file is automatically generated by SoC Online         */
/*                                                                       */
/*                            C Header File                              */
/*                                                                       */
/*                      !!! DO NOT MODIFY MANUALLY !!!                   */
/*                                                                       */
/*************************************************************************/
#ifndef _REGS_H_
#define _REGS_H_

#include "compiler.h"
#include "reg_agc_ram.h"
#include "reg_mac_hw.h"
#include "reg_riu.h"
#include "reg_ricu.h"
#include "reg_rfic_regs.h"
#include "reg_macdsp_api.h"
#include "reg_macsys_gcu.h"
#include "reg_lmac.h"
#include "reg_umac.h"
#include "reg_smac.h"
#include "reg_shared_ram.h"
#include "reg_access.h"
#include "compiler.h"
#include "arch.h"
#include "reg_mac_hw0_mu0.h"

#endif //_REGS_H_
