set(EMC_STD "STD" CACHE STRING "")
set_property(CACHE EMC_STD PROPERTY STRINGS "STD" "EMULATE")

set(EMC_STD_ASSERT ${EMC_STD} CACHE STRING "")
set_property(CACHE EMC_STD_ASSERT PROPERTY STRINGS "NONE" "EMULATE" "STD")

set(EMC_STD_ASSERT_ABI "NONE" CACHE STRING "")
set_property(CACHE EMC_STD_ASSERT_ABI PROPERTY STRINGS "NONE" "AEABI" "BIONIC")

set(EMC_STD_ASSERT_IMPL "ABORT" CACHE STRING "")
set_property(CACHE EMC_STD_ASSERT_IMPL PROPERTY STRINGS "HANDLER" "ABORT" "LOG" "MEM" "CPP_LOG")

option(EMC_STD_ASSERT_CONTEXT "" FALSE)
option(EMC_STD_ASSERT_MESSAGE "" TRUE)
option(EMC_STD_ASSERT_FUNCTION "" TRUE)

set(EMC_STD_ASSERT_SRC_POS "FILE_LINE" CACHE STRING "")
set_property(CACHE EMC_STD_ASSERT_SRC_POS PROPERTY STRINGS "FILE_LINE" "PROGRAM_COUNT" "HASH")

set(EMC_STD_ATOMIC ${EMC_STD} CACHE STRING "")
set_property(CACHE EMC_STD_ATOMIC PROPERTY STRINGS "STD" "EMULATE" "IMC" "NULL" "PSEUDO" "XTOS")

#set(EMC_STD_STDIO ${EMC_STD} CACHE STRING "")
set(EMC_STD_STDIO "STD" CACHE STRING "")
set_property(CACHE EMC_STD_STDIO PROPERTY STRINGS "NONE" "STD" "EMULATE")

set(EMC_STD_STDLIB ${EMC_STD} CACHE STRING "")
set_property(CACHE EMC_STD_STDLIB PROPERTY STRINGS "STD" "EMULATE")

set(EMC_STD_MALLOC "STD" CACHE STRING "")
set_property(CACHE EMC_STD_MALLOC PROPERTY STRINGS "tlsf" "ALTERA" "AMS" "XALLOC" "GKI" "m4osa" "SANDISK" "THREADX" "rcx" "STD" "NONE" "XTOS")

set(EMC_STD_MALLOC_LOCK "SPINLOCK" CACHE STRING "")
set_property(CACHE EMC_STD_MALLOC_LOCK PROPERTY STRINGS "SPINLOCK" "MUTEX")

set(EMC_STD_MALLOC_HEAP_SIZE "1474560" CACHE STRING "")

set(EMC_STD_MALLOC_HEAP_TRACE_SIZE "0" CACHE STRING "")

set(EMC_STD_DMA_MALLOC "STD" CACHE STRING "")
set_property(CACHE EMC_STD_MALLOC PROPERTY STRINGS "ALIGNED" "tlsf" "UTA" "STD" "NONE")


set(EMC_STD_MUTEX "NONE" CACHE STRING "")
set_property(CACHE EMC_STD_MUTEX PROPERTY STRINGS "NONE" "null" "mock" "STD" "pthreads" "uta" "xtos" "embos" "extern")

set(EMC_STD_SPINLOCK ${EMC_STD_MUTEX} CACHE STRING "")
set_property(CACHE EMC_STD_SPINLOCK PROPERTY STRINGS  "NONE" "null" "mock" "STD" "pthreads" "uta" "embos" "extern")


set(EMC_STD_TIMESTAMP "null" CACHE STRING "")
set_property(CACHE EMC_STD_TIMESTAMP PROPERTY STRINGS "null" "std" "net_emsys" "pthreads" "uta" "windows" "embos" "freertos" "xtos" "wdk" "xilinx" "extern")

#set(EMC_TARGET_OS_API "" CACHE STRING "")

