#ifndef __CECLI_H
#define __CECLI_H

// All the below must be aligned with kernel
#define CLI_MAX_PARAMS 32

//Ported from cl_rfic.c
#define RF_CMD_MAX_LEN 64

struct cli_params {
	uint32_t num_params;
	char option;
	int32_t params[CLI_MAX_PARAMS];
};

enum cl_cecli_cmd {
	CL_CECLI_AGC_PARAMS,
	CL_CECLI_BF,
	CL_CECLI_BSR,
	CL_CECLI_BSRP,
	CL_CECLI_BSS_COLOR,
	CL_CECLI_BW_SIG,
	CL_CECLI_CCA,
	CL_CECLI_CHIP,
	CL_CECLI_CMA,
	CL_CECLI_CONFIG,
	CL_CECLI_DEBUG,
	CL_CECLI_DUAL_NAV,
	CL_CECLI_EDCA,
	CL_CECLI_ENVDET,
	CL_CECLI_FW,
	CL_CECLI_IGMP,
	CL_CECLI_LCU,
	CL_CECLI_MORE_DATA,
	CL_CECLI_NCO,
	CL_CECLI_NOISE,
	CL_CECLI_OMI,
	CL_CECLI_POWER,
	CL_CECLI_QOS,
	CL_CECLI_RADIO,
	CL_CECLI_REG,
	CL_CECLI_RFIC,
	CL_CECLI_RSSI,
	CL_CECLI_RXSENS,
	CL_CECLI_RX_FILTER,
	CL_CECLI_SOUNDING,
	CL_CECLI_STATS,
	CL_CECLI_TCV,
	CL_CECLI_TEMP,
	CL_CECLI_TF,
	CL_CECLI_TIM,
	CL_CECLI_TRAFFIC,
	CL_CECLI_TWT,
	CL_CECLI_TX,
	CL_CECLI_TXQ,
	CL_CECLI_UL_RSSI,
	CL_CECLI_VERSION,
	CL_CECLI_VNS,
	CL_CECLI_VW,
	CL_CECLI_WRS,
	CL_CECLI_OTP,
	CL_CECLI_CALIB,

	CL_CECLI_MAX
};
#endif // __CECLI_H
