option(EMC_HW_PORT_INLINE_MMIO "" FALSE)
option(EMC_HW_PORT_VTBL_MMIO "" TRUE)

option(EMC_HW_PORT_READ_HOOK "" FALSE)
option(EMC_HW_PORT_WRITE_HOOK "" FALSE)

option(EMC_MEMORY_POOL_TYPE_XTOS "" FALSE)
option(EMC_MEMORY_POOL_TYPE_TLSF "" FALSE)
option(EMC_MEMORY_POOL_TYPE_MALLOC "" FALSE)
option(EMC_MEMORY_POOL_TYPE_STATIC "" FALSE)
option(EMC_MEMORY_POOL_TYPE_UNCACHED "" TRUE)

set(EMC_MEMORY_POOL_TYPE_STATIC_INSTANCES "2" CACHE STRING "")

set(EMC_HW_PHYSICAL_ADDRESS_MAP "PSEUDO" CACHE STRING "")
set_property(CACHE EMC_HW_PHYSICAL_ADDRESS_MAP PROPERTY STRINGS "PSEUDO" "NONE" "EXTERN")


