set(EMC_LOG "INTERNAL" CACHE STRING "")
set_property(CACHE EMC_LOG PROPERTY STRINGS "NONE" "INTERNAL" "EMCPP" "KPRINT" "LOG4C" "CUSTOMER")

set(EMC_LOG_INTERNAL_APPENDER_MEMORY_INSTANCES  "0" CACHE STRING "")
set(EMC_LOG_INTERNAL_APPENDER_PRINTF_INSTANCES  "0" CACHE STRING "")
set(EMC_LOG_INTERNAL_APPENDER_UART_INSTANCES  "0" CACHE STRING "")
set(EMC_LOG_INTERNAL_APPENDER_BUFFERED_TRANSPORT_INSTANCES  "0" CACHE STRING "")

if (EMC_LOG STREQUAL "NONE")
  set(EMC_LOG_LEVEL "FATAL" CACHE STRING "")
else()
  set(EMC_LOG_LEVEL "WARN" CACHE STRING "")
endif()
set_property(CACHE EMC_LOG_LEVEL PROPERTY STRINGS TRACE DEBUG INFO WARN ERROR FATAL)

set(EMC_LOG_INTERNAL_INSTANCES  "32" CACHE STRING "")
option(EMC_LOG_INTERNAL_HAS_CONFIGURE "" FALSE)

option(EMC_LOG_INTERNAL_USES_PC "The source position is determined by program counter" FALSE)
option(EMC_LOG_INTERNAL_USES_FILE "The source position uses __FILE__ for exact position" FALSE)
option(EMC_LOG_INTERNAL_USES_TIMESTAMP "The timestamp will be determined and stored in the record" FALSE)

option(EMC_LOG_USES_HASH "" FALSE)
option(EMC_LOG_PROFILE "" FALSE)
option(EMC_LOG_SYS_PROFILE "" FALSE)
option(EMC_LOG_DETAILED_PROFILING "" FALSE)



