PROJECT.ROOT.PATHNAME ?= ../../..

include $(PROJECT.ROOT.PATHNAME)/../eme/makefiles/makefile_setup.mk

PROJECT.MAIN.TARGET.LIB.NAME  = libcunit

SUBDIRS :=

SOURCES := 
SOURCES += Curses.c

include $(MAKE.DIR)/makefile_emsys.mk
