set(EMC_USB_LOG_LEVEL ${EMC_LOG_LEVEL} CACHE STRING "")
set_property(CACHE EMC_USB_LOG_LEVEL PROPERTY STRINGS "TRACE" "DEBUG" "INFO" "WARN" "ERROR" "FATAL" "OFF")

set(EMC_USB_MAX_SPEED "FULL" CACHE STRING "")
set_property(CACHE EMC_USB_MAX_SPEED PROPERTY STRINGS "FULL" "HIGH" "SUPER" "SUPER_PLUS")

option(EMC_USB_ROLE_DEVICE "" FALSE)
option(EMC_USB_ROLE_HOST "" FALSE)
