PROJECT.ROOT.PATHNAME ?= ../../..

include $(PROJECT.ROOT.PATHNAME)/../eme/makefiles/makefile_setup.mk

PROJECT.MAIN.TARGET.LIB.NAME  = libcunit

SUBDIRS :=

SOURCES := 
SOURCES += CUError.c
SOURCES += MyMem.c
SOURCES += Util.c
SOURCES += TestDB.c
SOURCES += TestRun.c

include $(MAKE.DIR)/makefile_emsys.mk
