set(EMC_OS NONE CACHE STRING "")
set(EMC_STD_MUTEX "mock" CACHE STRING "")
set(EMC_STD_SPINLOCK "mock" CACHE STRING "")
set(EMC_STD_ATOMIC "PSEUDO" CACHE STRING "")
set(EMC_STD_MALLOC "tlsf" CACHE STRING "")
set(EMC_STD_DMA_MALLOC "NONE" CACHE STRING "")

if (CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(EMC_STD_MALLOC_HEAP_SIZE "(8*1024)" CACHE STRING "") 

  set(EMC_STD_TIMESTAMP "pthreads" CACHE STRING "")
  eme_add_prerequisites(external_posix)

else()
  set(EMC_STD_MALLOC_HEAP_SIZE "(4*1024)" CACHE STRING "") 

  set(EMC_STD_TIMESTAMP "EXTERN" CACHE STRING "")
endif()

if (CMAKE_SYSTEM_NAME STREQUAL "Generic")
  set(EMC_STD "EMULATE" CACHE STRING "")
endif()
