option(EMC_USB_ROLE_DEVICE "" TRUE)

option(EMC_USB_DEVICE_HAL_EMC_DRIVER_UPDATES_TX_FIFO_CONFIG "" FALSE)
option(EMC_USB_DRIVER_DWC3_UPDATES_TX_FIFO_CONFIG "" ${EMC_USB_DEVICE_HAL_EMC_DRIVER_UPDATES_TX_FIFO_CONFIG})

set(EMC_USB_DEVICE_MAX_INTERFACE ${EMC_VENDOR_CELENO_USB_IF_COUNT} CACHE STRING "")

set(EMC_USB_MAX_SPEED "SUPER" CACHE STRING "")
set(EMC_USB_DEVICE_REQUEST_CHECK "STRICT" CACHE STRING "")

option(EMC_USB_DEVICE_PROCESS_HANDLING "" TRUE)
set(EMC_USB_PORT_ARCH "NONE" CACHE STRING "")

option(EMC_USB_DEVICE_HAL_EMC_DRIVER "" TRUE)

option(EMC_USB_DEVICE_DRIVER_DWC3 "" TRUE)

option(EMC_USB_DRIVER_FTABLE "" FALSE)
option(EMC_USB_DRIVER_HIBERNATION_SUPPORTED "" OFF)
option(EMC_USB_DRIVER_EP_CONTINUOUS_CHANNEL_SUPPORTED "" OFF)
option(EMC_USB_DRIVER_EP_SHARED_BUFFER_SUPPORTED "" OFF)
option(EMC_USB_DRIVER_EP_POLLING_SUPPORTED "" OFF)
option(EMC_USB_DRIVER_EP_USES_ASIO_BUFFERS_ITERATION "" OFF)
set(EMC_USB_DRIVER_ASIO_BUFFERS_PER_REQUEST "20" CACHE STRING "")

if (NOT EMCPP_TEST)
  option(EMC_HW_PORT_INLINE_MMIO "" TRUE)
  option(EMC_HW_PORT_VTBL_MMIO "" OFF)
else()
  option(EMC_HW_PORT_INLINE_MMIO "" OFF)
  option(EMC_HW_PORT_VTBL_MMIO "" TRUE)

  option(EMC_HW_PORT_READ_HOOK "" TRUE)
  option(EMC_HW_PORT_WRITE_HOOK "" TRUE)
endif()

option(EMC_MEMORY_POOL_TYPE_TLSF "" TRUE)
option(EMC_MEMORY_POOL_TYPE_MALLOC "" OFF)
option(EMC_MEMORY_POOL_TYPE_UNCACHED "" OFF)

eme_add_prerequisites(emc_usb_device_hal_emc_driver)
